function schema(conn)
%SB_GRID_TESTBENCH.DB.SCHEMA  Ensure the `results` table exists (idempotent).
%
%   sb_grid_testbench.db.schema(conn)
%
% Creates the results table per contract 3 if it is not already present. Safe to
% call repeatedly (CREATE TABLE IF NOT EXISTS). `conn` is an open built-in
% `sqlite` connection (see sb_grid_testbench.db.open_db).
%
% Dedup identity is UNIQUE(sim_version, param_hash): one row per (engine
% version, canonical params). Scalar params + metrics live here; full traces
% are saved separately to results/raw/<param_hash>.mat (trace_path).

sql = [ ...
 'CREATE TABLE IF NOT EXISTS results (' ...
 '  id           INTEGER PRIMARY KEY AUTOINCREMENT,' ...
 '  sim_version  TEXT NOT NULL,' ...
 '  param_hash   TEXT NOT NULL,' ...
 '  load_type    TEXT,' ...
 '  scr          REAL,' ...
 '  m            REAL,' ...
 '  dist_dp      REAL,' ...
 '  dp_mw        REAL,' ...
 '  dist_time    REAL,' ...
 '  stop_time    REAL,' ...
 '  settle_time  REAL,' ...
 '  p_w          REAL,' ...
 '  pfrq         REAL,' ...
 '  rocof        REAL,' ...
 '  nadir        REAL,' ...
 '  dip          REAL,' ...
 '  settle       REAL,' ...
 '  f0           REAL,' ...
 '  vbase        REAL,' ...
 '  t_nadir      REAL,' ...
 '  trace_path   TEXT,' ...
 '  created_at   TEXT,' ...
 '  UNIQUE(sim_version, param_hash)' ...
 ')'];

execute(conn, sql);
end
